# Generated by Django 4.0.5 on 2022-06-27 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escola', '0002_curso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='student',
        ),
        migrations.AddField(
            model_name='curso',
            name='student',
            field=models.ManyToManyField(limit_choices_to={'groups__name': 'Alunos'}, to=settings.AUTH_USER_MODEL),
        ),
    ]
